#!/bin/bash

echo "🚀 新的构建已触发！"
echo ""
echo "由于GitHub API速率限制，请通过以下方式查看构建状态："
echo ""
echo "1. 🌐 访问GitHub Actions页面："
echo "   https://github.com/iechor-research/research-cli/actions"
echo ""
echo "2. 🔍 查找最新的 'Build Native Wrapper' 工作流"
echo ""
echo "3. ⏳ 等待所有job完成（通常需要5-10分钟）"
echo ""
echo "4. ✅ 构建成功后，使用以下命令安装："
echo "   curl -sSL https://github.com/iechor-research/research-cli/releases/download/v0.2.7-native/install.sh | bash"
echo ""
echo "构建ID应该是最新的，创建时间在几分钟内。"
echo ""
echo "💡 提示：如果构建失败，查看'Create Release'步骤的日志以了解详情。" 