name: Generate Weekly Community Report 📊

on:
  schedule:
    - cron: '0 12 * * 1' # Run at 12:00 UTC on Monday
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to look back for the report'
        required: true
        default: '7'

jobs:
  generate-report:
    name: Generate Report 📝
    if: ${{ github.repository == 'iechor-research/research-cli' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
      discussions: read
      contents: read
      id-token: write

    steps:
      - name: Generate Report 📜
        id: report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          DAYS: ${{ github.event.inputs.days || '7' }}
        run: |
          set -e

          START_DATE=$(date -u -d "$DAYS days ago" +'%Y-%m-%d')
          END_DATE=$(date -u +'%Y-%m-%d')
          echo "⏳ Generating report for contributions from $START_DATE to $END_DATE..."

          declare -A author_is_iechorr
          check_iechorr_status() {
              local author=$1
              if [[ "$author" == *"[bot]" ]]; then
                  author_is_iechorr[$author]=1
                  return 1
              fi
              if [[ -v "author_is_iechorr[$author]" ]]; then
                  return ${author_is_iechorr[$author]}
              fi

              if gh api "orgs/iechorrs/members/$author" --silent 2>/dev/null; then
                  echo "🧑‍💻 $author is a iEchorr."
                  author_is_iechorr[$author]=0
              else
                  echo "🌍 $author is a community contributor."
                  author_is_iechorr[$author]=1
              fi
              return ${author_is_iechorr[$author]}
          }

          iechorr_issues=0
          non_iechorr_issues=0
          iechorr_prs=0
          non_iechorr_prs=0

          echo "🔎 Fetching issues and pull requests..."
          ITEMS_JSON=$(gh search issues --repo "$REPO" "created:>$START_DATE" --json author,isPullRequest --limit 1000)

          for row in $(echo "${ITEMS_JSON}" | jq -r '.[] | @base64'); do
              _jq() {
                  echo ${row} | base64 --decode | jq -r ${1}
              }
              author=$(_jq '.author.login')
              is_pr=$(_jq '.isPullRequest')

              if [[ -z "$author" || "$author" == "null" ]]; then
                continue
              fi

              if check_iechorr_status "$author"; then
                  if [[ "$is_pr" == "true" ]]; then
                      ((iechorr_prs++))
                  else
                      ((iechorr_issues++))
                  fi
              else
                  if [[ "$is_pr" == "true" ]]; then
                      ((non_iechorr_prs++))
                  else
                      ((non_iechorr_issues++))
                  fi
              fi
          done

          iechorr_discussions=0
          non_iechorr_discussions=0

          echo "🗣️ Fetching discussions..."
          DISCUSSION_QUERY='''
          query($q: String!) {
            search(query: $q, type: DISCUSSION, first: 100) {
              nodes {
                ... on Discussion {
                  author {
                    login
                  }
                }
              }
            }
          }'''
          DISCUSSIONS_JSON=$(gh api graphql -f q="repo:$REPO created:>$START_DATE" -f query="$DISCUSSION_QUERY")

          for row in $(echo "${DISCUSSIONS_JSON}" | jq -r '.data.search.nodes[] | @base64'); do
              _jq() {
                  echo ${row} | base64 --decode | jq -r ${1}
              }
              author=$(_jq '.author.login')

              if [[ -z "$author" || "$author" == "null" ]]; then
                continue
              fi

              if check_iechorr_status "$author"; then
                  ((iechorr_discussions++))
              else
                  ((non_iechorr_discussions++))
              fi
          done

          echo "✍️ Generating report content..."
          REPORT_TITLE="Community Contribution Report: $START_DATE to $END_DATE"
          TOTAL_ISSUES=$((iechorr_issues + non_iechorr_issues))
          TOTAL_PRS=$((iechorr_prs + non_iechorr_prs))
          TOTAL_DISCUSSIONS=$((iechorr_discussions + non_iechorr_discussions))

          REPORT_BODY=$(cat <<EOF
          ### 💖 Community Contribution Report

          **Period:** $START_DATE to $END_DATE

          | Category | iEchorrs | Community | Total |
          |---|---:|---:|---:|
          | **Issues** | $iechorr_issues | $non_iechorr_issues | **$TOTAL_ISSUES** |
          | **Pull Requests** | $iechorr_prs | $non_iechorr_prs | **$TOTAL_PRS** |
          | **Discussions** | $iechorr_discussions | $non_iechorr_discussions | **$TOTAL_DISCUSSIONS** |

          _This report was generated automatically by a GitHub Action._
          EOF
          )

          echo "report_body<<EOF" >> $GITHUB_OUTPUT
          echo "$REPORT_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "📊 Community Contribution Report:"
          echo "$REPORT_BODY"

      - name: 🤖 Get Insights from Report
        if: steps.report.outputs.report_body != ''
        uses: iechor-research/research-cli-action@df3f890f003d28c60a2a09d2c29e0126e4d1e2ff
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          version: 0.1.8-rc.0
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY  }}
          OTLP_GCP_WIF_PROVIDER: ${{ secrets.OTLP_GCP_WIF_PROVIDER }}
          OTLP_GOOGLE_CLOUD_PROJECT: ${{ secrets.OTLP_GOOGLE_CLOUD_PROJECT }}
          settings_json: |
            {
              "coreTools": [
                "run_shell_command(gh issue list)",
                "run_shell_command(gh pr list)",
                "run_shell_command(gh search issues)",
                "run_shell_command(gh search prs)"
              ]
            }
          prompt: |
            You are a helpful assistant that analyzes community contribution reports.
            Based on the following report, please provide a brief summary and highlight any interesting trends or potential areas for improvement.

            Report:
            ${{ steps.report.outputs.report_body }}
